version: '3.8'

services:
  web:
    build: .
    ports:
      - "5100:5100"
    env_file:
      - .env 
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    command: gunicorn -b 0.0.0.0:5100 app:app
